Messages = new (Meteor.Collection)('messages')
if Meteor.isClient
	# Setup any click events in this template
	Template.main.events
		'click #send_button': ->
			if console != 'undefined'
				console.log 'Sending message: ' + $('#message_input').val()
			name = $('#name_input').val() or '<<anonymous>>'
			Messages.insert
				name: name
				content: $('#message_input').val()
				likes: 0
				time: (new Date).getTime()
			$('#message_input').val ''
			return
		'click #clear_button': ->
			Meteor.call 'clear_all_messages'
			return
		'click .like_button': ->
			Messages.update @_id, $inc: likes: 1
			return
	# Setup any helper functions for this template
	Template.main.helpers 'locale_time': (epoch_time) ->
		new Date(epoch_time).toLocaleString()
	# Get all messages, in descending chronological order

	Template.main.message_list = ->
		Messages.find {}, sort: time: -1

if Meteor.isServer
	Meteor.startup ->
		Meteor.methods 'clear_all_messages': ->
			Messages.remove {}

# ---
# generated by js2coffee 2.0.3